# Generated by Django 4.2.6 on 2023-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Уровень сети', 'verbose_name_plural': 'Уровни сети'},
        ),
        migrations.AlterField(
            model_name='structure',
            name='hierarchy',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Уровень звена'),
        ),
    ]
